version = 1
SPDX-PackageName = "ZPKG_ABAP_BJ"
SPDX-PackageSupplier = "basant.joshi@inveniolsi.com"
SPDX-PackageDownloadLocation = "https://github.com/BasantJoshi01/ABAPROOMSOLUTION"
SPDX-PackageComment = "This Include All cds and requirements need to be fulfill."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and sap-community-abap-developer-challenge contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"